export const CHANNEL_ICONS: Record<string, string> = {
  weixin: "💚",
  wecom: "🏢",
  web: "💬",
  telegram: "✈️",
  whatsapp: "💬",
  discord: "🎮",
  feishu: "🐦",
  dingtalk: "🔔",
  email: "📧",
  slack: "⚡",
  qq: "🐧",
  matrix: "🔷",
  mochat: "💼",
};
